### ISSUE TITLE
Some variables in dataset.py seem to have been used without being defined.

### ISSUE THREAD

**Issue by HuXinjing** [JL-er/RWKV-PEFT#14]
https://github.com/JL-er/RWKV-PEFT/blob/e07c091a4b2813b5653d17117ea080cd74606f02/src/dataset.py#L106
It seems global_rank, real_epoch, world_size, devices is unavailable in MyDataset's self.

**Comment by HuXinjing** [comment]
I find num_workers > 0 could cause those variables being miss  assigned.

**Comment by JL-er** [comment]
It has now been replaced with the latest version of Lightning.
